set path "C:/Users/kim/Desktop/Personal/LPBF_LCA"
set python "C:/Users/kim/.conda/envs/bw2/python.exe"
puts "what happened"
puts "what happened"
exec "C:/Users/kim/.conda/envs/bw2/python.exe" "$path/AM_LCA.py"
puts "what happened"